### ISSUE TITLE
Unable to resolve some modules in Meteor 1.3

### ISSUE THREAD

**Issue by JakeHartnell** [peerlibrary/meteor-util#2]
Just upgraded to Meteor 1.3 which now has support for npm modules, but meteor-util is now throwing an error:

```

Unable to resolve some modules:

  "internal/util" in                          
/home/jake/.meteor/packages/peerlibrary_util/.0.3.0.1w12uq2++os+web.browser+web.cordova/web.browser/node.js/lib/util.js
(web.browser)

Consider running: meteor npm install --save internal

```

I'll keep troubleshooting to see if I can resolve the issue...

**Comment by mitar** [comment]
Hm, maybe also report it to the Meteor? This seems like a regression?

**Comment by JakeHartnell** [comment]
Maybe, looks like there [were some similar issues](https://github.com/meteor/meteor/issues/6601). On the client console we are getting:

```

Error: Cannot find module 'buffer'
 modules-runtime.js:95:19
TypeError: Package["peerlibrary:util"] is undefined
 peerlibrary_peerdb.js:25:5
TypeError: Package["peerlibrary:peerdb"] is undefined
```

**Comment by mitar** [comment]
Any progress?

**Comment by mitar** [comment]
I opened: https://github.com/meteor/meteor/issues/6680

**Comment by JakeHartnell** [comment]
Cool, thanks @mitar. I've reverted back to 1.2 land for now since I've got a demo I'm showing at the end of the week.

**Comment by JakeHartnell** [comment]
Works with Meteor 1.3.1

**Comment by mitar** [comment]
Are you sure this works? Because I do not get warnings on the server side in the console, but the client side is still complaining about the missing `util` in the web console.

**Comment by JakeHartnell** [comment]
My bad, I closed it too quickly before I had updated my packages properly. : /

**Comment by MatejJan** [comment]
Same problem here. I guess going back is the only thing for us with demos at the end of this week. :)

**Comment by mitar** [comment]
Upvote that Meteor ticket!

**Comment by mitar** [comment]
This one: https://github.com/meteor/meteor/issues/6680

**Comment by mitar** [comment]
Fixed with: 09840db50fd8caebb25699afe5ecd6653202d6f0
